#!/bin/bash
echo "===Resetting BLE ==="
echo "Power off ble"
sudo ~/bluez-5.45/tools/btmgmt -i hci0 power off
sleep 3
echo "LE on"
sudo ~/bluez-5.45/tools/btmgmt -i hci0 le on
echo "Connectable on"
sudo ~/bluez-5.45/tools/btmgmt -i hci0 connectable on
echo "Setting name to Hyperwave"
sudo ~/bluez-5.45/tools/btmgmt -i hci0 name "Hyperwave"
echo "Advertising on"
sudo ~/bluez-5.45/tools/btmgmt -i hci0 advertising on
sleep 3
echo "Power On"
sudo ~/bluez-5.45/tools/btmgmt -i hci0 power on
sleep 3
echo "Status"
systemctl status bluetooth
echo "Done."
